### ISSUE TITLE
Can't find plugin on Gradle Plugin Portal

### ISSUE THREAD

**Issue by blshao84** [morganstanley/gradle-plugin-application#3]
searched 'com.ms.gradle.application' from https://plugins.gradle.org/ but seems nothing's there. 
![image](https://user-images.githubusercontent.com/3524805/199149522-5a1ffc11-d1f4-4b1c-8210-3e2024233186.png)

**Comment by pantherdd** [comment]
Correct, the plugin has not yet been published to Gradle Plugin Portal. I'm currently working on some pre-requisite administrative tasks.

**Comment by blshao84** [comment]
> Correct, the plugin has not yet been published to Gradle Plugin Portal. I'm currently working on some pre-requisite administrative tasks.

I just see a new release, is it published to the repo now?

**Comment by pantherdd** [comment]
It's pending approval by the maintainers of Gradle Plugin Portal.
See: https://blog.gradle.org/plugin-portal-validations

**Comment by pantherdd** [comment]
It is now available on Gradle Plugin Portal, just click the badge at the top of the main [`README`](https://github.com/morganstanley/gradle-plugin-application/blob/main/README.md). :)
